### PR TITLE
fix wrong boolean logic in ServiceTypeListener

### PR DESCRIPTION
**Pull request by bsideup**
Hi @gastaldi.

First of all, thanks for accepting #3 so fast, I didn't expect that :D 

However, after doing some morning code review for myself I found a stupid mistake / leftover after the inversion of boolean logic.

I'm going to add much more tests for this container where I'll cover `javax` injection as well, just a bit later, if you don't mind.

Thanks!

### CODE REVIEW

**Comment by bsideup** [comment]
Actually... This small fix breaks the integration. In fact, it was too naive and incorrect at all. I'll investigate now. Sorry :flushed:

**Comment by bsideup** [comment]
Weird. `isAnnotationPresent` returns `false`. It means that somehow annotations info is missing from the Class. I assume it somehow related to JBoss Modules?

**Comment by gastaldi** [comment]
Maybe they have different classloaders? Try printing the classloaders for the annotations and the Inject.class you are comparing

**Comment by bsideup** [comment]
@gastaldi I think I managed to fix that. Could you please take a look?

**Comment by gastaldi** [comment]
That might work, let's use that for now. Are you interested in having push access to the repository? Looks like you are the only one (besides me) working on this

**Comment by bsideup** [comment]
Test was failing because `javax.inject.Inject` was missing for the dependent addon, and Java strips such annotations during reflection calls, so I added it to the dependency addon, plus changed checks to string-based (to avoid classloading issues and leaking)

**Comment by bsideup** [comment]
Well, that would be good since I'm going to deliver more changes to it. 

Anyway, I really like the PR model and, if you don't mind, will send my changes as pull requests, ok?

**Comment by gastaldi** [comment]
Sure, no problems, always a pleasure :+1:

**Pull request merged**
